/**
 * PTE CONVERSION — Case Detect & Main Entry
 */
import { fuzzyMatchHeader } from '../../utils/fuzzy';
import { enrichWithRealType } from './caseA';
import { deriveWithLineKey, deriveWithoutLineKey } from './caseB';
import { twoPassOrphanSweep, pureOrphanSweep } from './caseD';
import { assembleElements } from './builder';
import { registerRule } from '../ruleRegistry';

// Register ONLY the PTE rules we actually have implemented (PTE-01, PTE-03, PTE-06, PTE-07, etc)
[
  "R-PTE-01", "R-PTE-03", "R-PTE-06", "R-PTE-07", "R-PTE-08", "R-PTE-09",
  "R-PTE-10", "R-PTE-11", "R-PTE-12", "R-PTE-20", "R-PTE-21", "R-PTE-22",
  "R-PTE-29", "R-PTE-31", "R-PTE-34", "R-PTE-41", "R-PTE-42", "R-PTE-50",
  "R-PTE-51", "R-PTE-52"
].forEach(ruleId => registerRule(ruleId));

function hasColumn(headers, name) {
  return fuzzyMatchHeader(name, headers) !== null;
}

export function selectPTECase(headers, rows, config) {
  const hasRef = hasColumn(headers, "RefNo");
  const hasPoint = hasColumn(headers, "Point");
  const hasPPoint = hasColumn(headers, "PPoint");

  const lineKeyCol = config.pte.lineKeyColumn || "Line_Key";
  const mappedLineKeyCol = fuzzyMatchHeader(lineKeyCol, headers);

  // Check if Line_Key is mapped and at least one row has a non-empty value for it
  let hasLineKeyValues = false;
  if (mappedLineKeyCol) {
    hasLineKeyValues = rows.some(r => r[mappedLineKeyCol] && r[mappedLineKeyCol].toString().trim() !== "");
  }

  const hasLineKey = config.pte.lineKeyEnabled && hasLineKeyValues;
  const isSequential = config.pte.sequentialData;

  if (hasRef && hasPoint && hasPPoint) return "CASE_A";
  if (isSequential && hasLineKey) return "CASE_B_a";
  if (isSequential && !hasLineKey) return "CASE_B_b";
  if (!isSequential && hasLineKey) return "CASE_D_a";
  return "CASE_D_b";
}

export function runPTEConversion(intermediateRows, config, log) {
  if (!intermediateRows || intermediateRows.length === 0) return [];

  const headers = Object.keys(intermediateRows[0]);
  const pteCase = selectPTECase(headers, intermediateRows, config);

  log.push({ type: "Info", message: `PTE Conversion started. Detected Case: ${pteCase}` });

  let resultTable = [];

  switch (pteCase) {
    case "CASE_A": {
      const enriched = enrichWithRealType(intermediateRows);
      const grouped = {};
      for (const row of enriched) {
        if (!row.RefNo) continue;
        if (!grouped[row.RefNo]) grouped[row.RefNo] = [];
        grouped[row.RefNo].push(row);
      }
      resultTable = assembleElements(grouped);
      break;
    }
    case "CASE_B_a":
    case "CASE_B_b": {
      const useLineKey = pteCase === "CASE_B_a";
      const derived = useLineKey ? deriveWithLineKey(intermediateRows) : deriveWithoutLineKey(intermediateRows);

      const grouped = {};
      for (const row of derived) {
        const ref = row.RefNo || row.refNo;
        if (!ref) continue;
        if (!grouped[ref]) grouped[ref] = [];
        grouped[ref].push(row);
      }
      resultTable = assembleElements(grouped);
      break;
    }
    case "CASE_D_a":
    case "CASE_D_b": {
      const useLineKey = pteCase === "CASE_D_a";
      resultTable = useLineKey ? twoPassOrphanSweep(intermediateRows, config, log) : pureOrphanSweep(intermediateRows, config, log);
      break;
    }
    default:
      log.push({ type: "Error", message: `Unknown PTE case: ${pteCase}` });
      return [];
  }

  // After elements are assembled, we map them to the Data Table schema
  return mapToDataTable(resultTable);
}

function mapToDataTable(elements) {
  // elements is an array of objects resembling the Data Table schema,
  // generated by caseA/B/D modules
  return elements.map((el, i) => ({
    ...el,
    _rowIndex: i + 1,
    _source: "PTE",
    _modified: el._modified || {},
    _logTags: el._logTags || [],
    csvSeqNo: el.csvSeqNo || null,
    type: (el.type || "").toUpperCase(),
    text: el.text || "",
    pipelineRef: el.pipelineRef || "",
    refNo: el.refNo || "",
    bore: el.bore || 0,
    ep1: el.ep1 || null,
    ep2: el.ep2 || null,
    cp: el.cp || null,
    bp: el.bp || null,
    branchBore: el.branchBore || null,
    skey: el.skey || "",
    supportCoor: el.supportCoor || null,
    supportName: el.supportName || "",
    supportGuid: el.supportGuid || "",
    ca: el.ca || {1:null, 2:null, 3:null, 4:null, 5:null, 6:null, 7:null, 8:null, 9:null, 10:null, 97:null, 98:null},
    fixingAction: "",
  }));
}
