/**
 * PTE CONVERSION — Case Detect & Main Entry
 */
import { fuzzyMatchHeader } from '../../utils/fuzzy';
import { enrichWithRealType } from './caseA';
import { deriveWithLineKey, deriveWithoutLineKey } from './caseB';
import { twoPassOrphanSweep, pureOrphanSweep } from './caseD';
import { registerRule, logRuleExecution } from '../ruleRegistry';

// Register ONLY the PTE rules we actually have implemented (PTE-01, PTE-03, PTE-06, PTE-07, etc)
[
  "R-PTE-01", "R-PTE-03", "R-PTE-06", "R-PTE-07", "R-PTE-08", "R-PTE-09",
  "R-PTE-10", "R-PTE-11", "R-PTE-12", "R-PTE-20", "R-PTE-21", "R-PTE-22",
  "R-PTE-29", "R-PTE-31", "R-PTE-34", "R-PTE-41", "R-PTE-42", "R-PTE-50",
  "R-PTE-51", "R-PTE-52"
].forEach(ruleId => registerRule(ruleId));

function hasColumn(headers, name) {
  return fuzzyMatchHeader(name, headers) !== null;
}

export function selectPTECase(headers, rows, config) {
  const hasRef = hasColumn(headers, "RefNo");
  const hasPoint = hasColumn(headers, "Point");
  const hasPPoint = hasColumn(headers, "PPoint");
  const hasLineKey = config.pte.lineKeyEnabled && hasColumn(headers, config.pte.lineKeyColumn || "Line_Key");
  const isSequential = config.pte.sequentialData;

  if (hasRef && hasPoint && hasPPoint) return "CASE_A";
  if (isSequential && hasLineKey) return "CASE_B_a";
  if (isSequential && !hasLineKey) return "CASE_B_b";
  if (!isSequential && hasLineKey) return "CASE_D_a";
  return "CASE_D_b";
}

export function runPTEConversion(intermediateRows, config, log) {
  if (!intermediateRows || intermediateRows.length === 0) return [];

  const headers = Object.keys(intermediateRows[0]);
  const pteCase = selectPTECase(headers, intermediateRows, config);

  log.push({ type: "Info", message: `PTE Conversion started. Detected Case: ${pteCase}` });

  let resultTable = [];

  switch (pteCase) {
    case "CASE_A": {
      // For now, Case A just enriches and returns raw rows for further pipeline,
      // but to map to elements, it must pass through processCaseB or similar grouping.
      // Assuming CASE_B processes enriched arrays for mapping.
      const enriched = enrichWithRealType(intermediateRows);
      resultTable = deriveWithLineKey(enriched, config);
      break;
    }
    case "CASE_B_a":
    case "CASE_B_b": {
      const useLineKey = pteCase === "CASE_B_a";
      resultTable = useLineKey ? deriveWithLineKey(intermediateRows, config) : deriveWithoutLineKey(intermediateRows, config);
      break;
    }
    case "CASE_D_a":
    case "CASE_D_b": {
      const useLineKey = pteCase === "CASE_D_a";
      resultTable = useLineKey ? twoPassOrphanSweep(intermediateRows, config, log) : pureOrphanSweep(intermediateRows, config, log);
      break;
    }
    default:
      log.push({ type: "Error", message: `Unknown PTE case: ${pteCase}` });
      return [];
  }

  // After elements are assembled, we map them to the Data Table schema
  return mapToDataTable(resultTable, config, log);
}

function mapToDataTable(elements, config, log) {
  // elements is an array of objects resembling the Data Table schema,
  // generated by caseA/B/D modules
  return elements.map((el, i) => ({
    ...el,
    _rowIndex: i + 1,
    _source: "PTE",
    _modified: el._modified || {},
    _logTags: el._logTags || [],
    csvSeqNo: el.csvSeqNo || null,
    type: (el.type || "").toUpperCase(),
    text: el.text || "",
    pipelineRef: el.pipelineRef || "",
    refNo: el.refNo || "",
    bore: el.bore || 0,
    ep1: el.ep1 || null,
    ep2: el.ep2 || null,
    cp: el.cp || null,
    bp: el.bp || null,
    branchBore: el.branchBore || null,
    skey: el.skey || "",
    supportCoor: el.supportCoor || null,
    supportName: el.supportName || "",
    supportGuid: el.supportGuid || "",
    ca: el.ca || {1:null, 2:null, 3:null, 4:null, 5:null, 6:null, 7:null, 8:null, 9:null, 10:null, 97:null, 98:null},
    fixingAction: "",
  }));
}
